### ISSUE TITLE
User Story: View Recent Posts

### ISSUE THREAD

**Issue by Al3xandruF** [Al3xandruF/CulinaryArt#22]
As a **developer**, I want to **see all recent posts**, So that **I can stay up to date with the newest content**.

### Criteria:

1. View recent posts.
2. Search posts.
3. Infinite Scroll.

### Tasks:

- [ ] Create a search bar.
- [ ] Display all posts.
- [ ] Implement infinite functionality.
