### ISSUE TITLE
User Story: Chef_Bio

### ISSUE THREAD

**Issue by Al3xandruF** [Al3xandruF/CulinaryArt#34]
As a **chef user**, I want to **be able to add my details on my profile page**, So that **other users could see it and if interested, reach out for other recipes or advice**.

### Criteria:

1. Only Chef accounts can create their Bio.
2. All users can see the Chef's bio displayed.
3. Chef can apply CRUD functionality to their bio.

### Tasks:

- [ ] Create a Chef_Bio create form.
- [ ] Create a Chef_Bio edit form.
- [ ] Set up permissions for Chef accounts.
